### ISSUE TITLE
Feature: support docker-ce / docker-ee

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-role-srv_docker#2]
Supporting docker-ce and docker-ee is recommended for Version 2.0.0

**Comment by daniel-schier** [comment]
for docker-ce and docker-ee there are currently some needed steps:

- remove all docker packages
- optionally remove content from /var/lib/docker
- setting up the repository (dedicated role?)
- there are test and nightly repositories, too (dedicated role?)
- service and firewall behaviour does not change with docker-ce or docker-ee

behaviour for centos and fedora is the same.

**Comment by daniel-schier** [comment]
ref: https://docs.docker.com/install/linux/docker-ce/fedora/
ref: https://docs.docker.com/install/linux/docker-ee/centos/
