### ISSUE TITLE
Feature: support docker-compose

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-role-srv_docker#3]
As a developer, I want to be able to use additional development support ala app_bash with docker-compose and maybe some other tools.

**Comment by daniel-schier** [comment]
for fedora: it's in the repositories
for centos: binary must be downloaded

+ there is also an option for pip

this will result into:

- option for binary or repository
- automatic usage of binary for distributions, not having docker-compose
- optional supporting pip, which is kind of tricky and the better approach for user-pip-environments.

**Comment by daniel-schier** [comment]
ref: https://docs.docker.com/compose/install/
